# **Making the DataFrame**

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_example = {"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]}
pd.DataFrame(data_example)

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

# **Read Data from File**

In [5]:
#df = pd.read_csv("data.csv")
df = pd.read_csv("cereal.csv")

In [6]:
df.head() #to show the top 5 data

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.0,0.75,34.384843

In [7]:
df.head(n=10) #to shop the top ten

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.00,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.00,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.00,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.00,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,FDA_25,1,1.00,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14.0,30.0,FDA_25,2,1.00,1.00,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18.0,8.0,100.0,FDA_25,3,1.33,0.75,37.038562
8,Bran Chex,R,C,90,2,1,200,4.0,15.0,6.0,125.0,FDA_25,1,1.00,0.67,49.120253
9,Bran Flakes,P,C,90,3,0,210,5.0,13.0,5.0,190.0,FDA_25,3,1.00,0.67,53.313813

In [8]:
df.tail() #to show the bottom five

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,FDA_25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,FDA_25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,FDA_25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,FDA_25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,FDA_25,1,1.0,0.75,36.187559

In [9]:
df.tail(n=10) #to show the bottom five

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
67,Special K,K,C,110,6,0,230,1.0,16.0,3.0,55.0,FDA_25,1,1.0,1.00,53.131324
68,Strawberry Fruit Wheats,N,C,90,2,0,15,3.0,15.0,5.0,90.0,FDA_25,2,1.0,1.00,59.363993
69,Total Corn Flakes,G,C,110,2,1,200,0.0,21.0,3.0,35.0,FDA_100,3,1.0,1.00,38.839746
70,Total Raisin Bran,G,C,140,3,1,190,4.0,15.0,14.0,230.0,FDA_100,3,1.5,1.00,28.592785
71,Total Whole Grain,G,C,100,3,1,200,3.0,16.0,3.0,110.0,FDA_100,3,1.0,1.00,46.658844
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,FDA_25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,FDA_25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,FDA_25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,FDA_25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,FDA_25,1,1.0,0.75,36.187559

In [10]:
df.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'rating'],
      dtype='object')

In [11]:
df.index

RangeIndex(start=0, stop=77, step=1)

In [12]:
df.shape

(77, 16)

# **Get Columns and Rows**

In [13]:
df.mfr #to show the column mfr only

0     N
1     Q
2     K
3     K
4     R
     ..
72    G
73    G
74    R
75    G
76    G
Name: mfr, Length: 77, dtype: object

In [14]:
df[['mfr', 'type', 'calories', 'protein']] #to how more than one columns

   mfr type  calories  protein
0    N    C        70        4
1    Q    C       120        3
2    K    C        70        4
3    K    C        50        4
4    R    C       110        2
..  ..  ...       ...      ...
72   G    C       110        2
73   G    C       110        1
74   R    C       100        3
75   G    C       100        3
76   G    C       110        2

[77 rows x 4 columns]

In [15]:
df[['mfr', 'type', 'calories', 'protein']].head() #to show more than one columns with top five

  mfr type  calories  protein
0   N    C        70        4
1   Q    C       120        3
2   K    C        70        4
3   K    C        50        4
4   R    C       110        2

In [16]:
df[['mfr', 'type', 'calories', 'protein']][5:10] #inclusive:exclusive slicing

  mfr type  calories  protein
5   G    C       110        2
6   K    C       110        2
7   G    C       130        3
8   R    C        90        2
9   P    C        90        3

# **Slicing with .loc and .iloc**

In [17]:
df.loc[1:4, "type": "sugars"] #the result of this slicing is not inclusive:exclusive
                              #because based on the name location

  type  calories  protein  fat  sodium  fiber  carbo  sugars
1    C       120        3    5      15    2.0    8.0     8.0
2    C        70        4    1     260    9.0    7.0     5.0
3    C        50        4    0     140   14.0    8.0     0.0
4    C       110        2    2     200    1.0   14.0     8.0

In [18]:
df.iloc[1:4, 3:6] #the result of this slicing is inclusive:exclusive
                  #because based on the index location

   calories  protein  fat
1       120        3    5
2        70        4    1
3        50        4    0

In [19]:
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.0,0.75,34.384843

# **Changing the Index Column**

In [21]:
df = pd.read_csv("cereal.csv", index_col="name")

In [22]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.0,0.75,34.384843

In [23]:
df['type']

name
100% Bran                    C
100% Natural Bran            C
All-Bran                     C
All-Bran with Extra Fiber    C
Almond Delight               C
                            ..
Triples                      C
Trix                         C
Wheat Chex                   C
Wheaties                     C
Wheaties Honey Gold          C
Name: type, Length: 77, dtype: object

In [24]:
#df.loc[1:4, "type": "sugars"] #it will return error because index is not int
df.loc["All-Bran":"Triples", "type": "sugars"]

,type,calories,protein,fat,sodium,fiber,carbo,sugars
name,,,,,,,,
All-Bran,C,70,4,1,260,9.0,7.0,5.0
All-Bran with Extra Fiber,C,50,4,0,140,14.0,8.0,0.0
Almond Delight,C,110,2,2,200,1.0,14.0,8.0
Apple Cinnamon Cheerios,C,110,2,2,180,1.5,10.5,10.0
Apple Jacks,C,110,2,0,125,1.0,11.0,14.0
...,...,...,...,...,...,...,...,...
Strawberry Fruit Wheats,C,90,2,0,15,3.0,15.0,5.0
Total Corn Flakes,C,110,2,1,200,0.0,21.0,3.0
Total Raisin Bran,C,140,3,1,190,4.0,15.0,14.0
Total Whole Grain,C,100,3,1,200,3.0,16.0,3.0
Triples,C,110,2,1,250,0.0,21.0,3.0

# **DataFrame Summary (stats)**

In [25]:
numeric_df = df.select_dtypes(include=np.number)
numeric_df.corr()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,shelf,weight,cups,rating
calories,1.000000,0.019066,0.498610,0.300649,-0.293413,0.257638,0.566533,-0.072063,0.097234,0.696091,0.087200,-0.689376
protein,0.019066,1.000000,0.208431,-0.054674,0.500330,-0.025012,-0.291853,0.563706,0.133865,0.216158,-0.244469,0.470618
fat,0.498610,0.208431,1.000000,-0.005407,0.016719,-0.300003,0.302497,0.200445,0.263691,0.214625,-0.175892,-0.409284
sodium,0.300649,-0.054674,-0.005407,1.000000,-0.070675,0.297687,0.058866,-0.042632,-0.069719,0.308576,0.119665,-0.401295
fiber,-0.293413,0.500330,0.016719,-0.070675,1.000000,-0.380357,-0.138760,0.911528,0.297539,0.247226,-0.513061,0.584160
carbo,0.257638,-0.025012,-0.300003,0.297687,-0.380357,1.000000,-0.471184,-0.365003,-0.192650,0.138467,0.367460,0.088712
sugars,0.566533,-0.291853,0.302497,0.058866,-0.138760,-0.471184,1.000000,0.001414,0.068377,0.455844,-0.048961,-0.763902
potass,-0.072063,0.563706,0.200445,-0.042632,0.911528,-0.365003,0.001414,1.000000,0.385784,0.419933,-0.501607,0.416009
shelf,0.097234,0.133865,0.263691,-0.069719,0.297539,-0.192650,0.068377,0.385784,1.000000,0.190762,-0.335269,0.025159
weight,0.696091,0.216158,0.214625,0.308576,0.247226,0.138467,0.455844,0.419933,0.190762,1.000000,-0.199583,-0.298124
cups,0.087200,-0.244469,-0.175892,0.119665,-0.513061,0.367460,-0.048961,-0.501607,-0.335269,-0.199583,1.000000,-0.203160
rating,-0.689376,0.470618,-0.409284,-0.401295,0.584160,0.088712,-0.763902,0.416009,0.025159,-0.298124,-0.203160,1.000000

In [26]:
df.describe().T #T for transpose

,count,mean,std,min,25%,50%,75%,max
calories,77.0,106.883117,19.484119,50.000000,100.000000,110.000000,110.000000,160.000000
protein,77.0,2.545455,1.094790,1.000000,2.000000,3.000000,3.000000,6.000000
fat,77.0,1.012987,1.006473,0.000000,0.000000,1.000000,2.000000,5.000000
sodium,77.0,159.675325,83.832295,0.000000,130.000000,180.000000,210.000000,320.000000
fiber,77.0,2.151948,2.383364,0.000000,1.000000,2.000000,3.000000,14.000000
carbo,76.0,14.802632,3.907326,5.000000,12.000000,14.500000,17.000000,23.000000
sugars,76.0,7.026316,4.378656,0.000000,3.000000,7.000000,11.000000,15.000000
potass,75.0,98.666667,70.410636,15.000000,42.500000,90.000000,120.000000,330.000000
shelf,77.0,2.207792,0.832524,1.000000,1.000000,2.000000,3.000000,3.000000
weight,77.0,1.029610,0.150477,0.500000,1.000000,1.000000,1.000000,1.500000
cups,77.0,0.821039,0.232716,0.250000,0.670000,0.750000,1.000000,1.500000
rating,77.0,42.665705,14.047289,18.042851,33.174094,40.400208,50.828392,93.704912

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77 entries, 100% Bran to Wheaties Honey Gold
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mfr       77 non-null     object
 1   type      77 non-null     object
 2   calories  77 non-null     int64
 3   protein   77 non-null     int64
 4   fat       77 non-null     int64
 5   sodium    77 non-null     int64
 6   fiber     77 non-null     float64
 7   carbo     76 non-null     float64
 8   sugars    76 non-null     float64
 9   potass    75 non-null     float64
 10  vitamins  77 non-null     object
 11  shelf     77 non-null     int64
 12  weight    77 non-null     float64
 13  cups      77 non-null     float64
 14  rating    77 non-null     float64
dtypes: float64(7), int64(5), object(3)
memory usage: 11.7+ KB

In [28]:
df.mfr.value_counts()

mfr
K    23
G    22
P     9
R     8
Q     8
N     6
A     1
Name: count, dtype: int64

In [29]:
#df.type.unique()
df.shelf.unique()

array([3, 1, 2])

In [30]:
df.nunique()

mfr          7
type         2
calories    11
protein      6
fat          5
sodium      27
fiber       13
carbo       21
sugars      16
potass      35
vitamins     3
shelf        3
weight       7
cups        12
rating      77
dtype: int64

# **NaN Value**

NaN = Not a Number

In [31]:
#df.isna()
df.isna().sum()

mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       1
sugars      1
potass      2
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [32]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.0,0.75,34.384843

In [33]:
df.dropna().head() #to drop the NaN data

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,FDA_25,1,1.0,0.75,29.509541

# **Data Imputation**

In [34]:
df.fillna("==ICT336==").head() #replacing the NaN with ==ICT336==

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,==ICT336==,FDA_25,3,1.0,0.75,34.384843

In [35]:
filler = {"carbo": "CARBO", "sugars": "SUGARS", "potass": "POTASS"}
df.fillna(filler).head() #to fill more than one columns

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,POTASS,FDA_25,3,1.0,0.75,34.384843

In [36]:
df.mean(numeric_only=True)

calories    106.883117
protein       2.545455
fat           1.012987
sodium      159.675325
fiber         2.151948
carbo        14.802632
sugars        7.026316
potass       98.666667
shelf         2.207792
weight        1.029610
cups          0.821039
rating       42.665705
dtype: float64

In [37]:
numeric_mean = numeric_df.mean(numeric_only=True)
df.fillna(numeric_mean).head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.000000,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.000000,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.000000,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.000000,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,98.666667,FDA_25,3,1.0,0.75,34.384843

In [38]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.0,0.75,34.384843

In [39]:
numeric_means = df.mean(numeric_only=True)
df.fillna(numeric_means, inplace=True)
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.000000,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.000000,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.000000,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.000000,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,98.666667,FDA_25,3,1.0,0.75,34.384843

In [40]:
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.000000,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.000000,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.000000,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.000000,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,98.666667,FDA_25,3,1.0,0.75,34.384843

In [41]:
df.to_csv("cereal_imputed.csv", index_label='name')
#df.to_csv("cereal_imputed.csv", index_label=None)